dataset:
  name: FrancForSeg
  dataset_path: /home/fzhcis/mylab/data/synthetic-lidar-point-clouds-tree-simulator/LiDAR-like-Dataset/
  train_test_split_json_dir: /home/fzhcis/mylab/data/synthetic-lidar-point-clouds-tree-simulator/LiDAR-like-Dataset/train_test_split/
  cache_dir: ./logs/cache/
  class_weights: [2_050_652, 12_852_250, 43_355_279, 62_201_819]
  test_result_folder: ./test
  use_cache: true
  steps_per_epoch_train: 500
  steps_per_epoch_valid: 50
model:
  name: KPFCNN
  ckpt_path: # path/to/your/checkpoint
  KP_extent: 1.2
  KP_influence: linear
  aggregation_mode: sum
  architecture:
  - simple
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb
  - resnetb_strided
  - resnetb
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  augment_color: 1.0
  augment_noise: 0.001
  augment_rotation: vertical
  augment_scale_anisotropic: true
  augment_scale_max: 1.1
  augment_scale_min: 0.9
  augment_symmetries:
  - true
  - false
  - false
  batch_limit: 10000
  batch_norm_momentum: 0.98
  batcher: ConcatBatcher
  conv_radius: 2.5
  deform_fitting_mode: point2point
  deform_fitting_power: 1.0
  deform_radius: 6.0
  density_parameter: 5.0
  first_features_dim: 128
  first_subsampling_dl: 0.06
  fixed_kernel_points: center
  ignored_label_inds: [0]
  in_features_dim: 4
  in_points_dim: 3
  in_radius: 6.0
  lbl_values: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  min_in_points: 5000
  max_in_points: 10000
  modulated: false
  num_classes: 8
  num_kernel_points: 15
  num_layers: 5
  repulse_extent: 1.2
  use_batch_norm: true
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 1
  learning_rate: 0.01
  lr_decays: 0.98477
  deform_lr_factor: 0.1
  main_log_dir: ./logs
  max_epoch: 500
  save_ckpt_freq: 5
  scheduler_gamma: 0.95
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
  weight_decay: 0.001
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
