#!/usr/bin/env python
"""Example script to read and analyze .las files generated by inference."""

import argparse
import numpy as np
from pathlib import Path

try:
    import laspy
except ImportError:
    print("ERROR: laspy not installed. Install with: pip install laspy")
    exit(1)


def analyze_las_file(las_path):
    """Read and analyze a LAS file with predictions."""
    print(f"\n{'='*70}")
    print(f"Analyzing: {las_path}")
    print(f"{'='*70}")
    
    # Read the LAS file
    las = laspy.read(las_path)
    
    # Extract data
    points = np.vstack([las.x, las.y, las.z]).T
    gt_labels = np.array(las.classification)
    pred_labels = np.array(las.user_data)
    
    # Basic statistics
    print(f"\nBasic Information:")
    print(f"  Total points: {len(las.x):,}")
    print(f"  Point format: {las.header.point_format}")
    print(f"  LAS version: {las.header.version}")
    
    # Coordinate ranges
    print(f"\nCoordinate Ranges:")
    print(f"  X: [{points[:, 0].min():.3f}, {points[:, 0].max():.3f}]")
    print(f"  Y: [{points[:, 1].min():.3f}, {points[:, 1].max():.3f}]")
    print(f"  Z: [{points[:, 2].min():.3f}, {points[:, 2].max():.3f}]")
    
    # RGB information
    if hasattr(las, 'red'):
        rgb = np.vstack([las.red, las.green, las.blue]).T
        print(f"\nRGB Colors:")
        print(f"  Range: 0-{rgb.max()}")
        print(f"  Mean: [{rgb[:, 0].mean():.0f}, {rgb[:, 1].mean():.0f}, {rgb[:, 2].mean():.0f}]")
    
    # Intensity information
    if hasattr(las, 'intensity'):
        print(f"\nIntensity:")
        print(f"  Range: [{las.intensity.min()}, {las.intensity.max()}]")
        print(f"  Mean: {las.intensity.mean():.2f}")
    
    # Ground truth labels
    gt_unique, gt_counts = np.unique(gt_labels, return_counts=True)
    print(f"\nGround Truth Labels (classification field):")
    print(f"  Unique labels: {gt_unique}")
    print(f"  Distribution:")
    semantic3d_labels = {
        0: 'unlabeled', 1: 'man-made terrain', 2: 'natural terrain',
        3: 'high vegetation', 4: 'low vegetation', 5: 'buildings',
        6: 'hard scape', 7: 'scanning artefacts', 8: 'cars'
    }
    for label, count in zip(gt_unique, gt_counts):
        pct = count / len(gt_labels) * 100
        label_name = semantic3d_labels.get(label, 'unknown')
        print(f"    {label} ({label_name:<20}): {count:>8,} ({pct:>5.2f}%)")
    
    # Predicted labels
    pred_unique, pred_counts = np.unique(pred_labels, return_counts=True)
    print(f"\nPredicted Labels (user_data field):")
    print(f"  Unique labels: {pred_unique}")
    print(f"  Distribution:")
    for label, count in zip(pred_unique, pred_counts):
        pct = count / len(pred_labels) * 100
        label_name = semantic3d_labels.get(label, 'unknown')
        print(f"    {label} ({label_name:<20}): {count:>8,} ({pct:>5.2f}%)")
    
    # Accuracy calculation (excluding unlabeled points)
    valid_mask = gt_labels != 0
    if valid_mask.sum() > 0:
        valid_gt = gt_labels[valid_mask]
        valid_pred = pred_labels[valid_mask]
        
        # Predictions are 1-8, need to align with GT for comparison
        correct = (valid_gt == valid_pred).sum()
        accuracy = correct / len(valid_gt) * 100
        
        print(f"\nAccuracy (excluding unlabeled):")
        print(f"  Valid points: {len(valid_gt):,}")
        print(f"  Correct predictions: {correct:,}")
        print(f"  Accuracy: {accuracy:.2f}%")
        
        # Per-class accuracy
        print(f"\nPer-Class Accuracy:")
        for label in sorted(np.unique(valid_gt)):
            mask = valid_gt == label
            if mask.sum() > 0:
                class_correct = (valid_pred[mask] == label).sum()
                class_total = mask.sum()
                class_acc = class_correct / class_total * 100
                label_name = semantic3d_labels.get(label, 'unknown')
                print(f"    {label} ({label_name:<20}): {class_acc:>6.2f}% ({class_correct:>6,}/{class_total:>6,})")
    
    print(f"\n{'='*70}\n")


def main():
    parser = argparse.ArgumentParser(
        description='Read and analyze LAS files with prediction results'
    )
    parser.add_argument(
        'las_files',
        type=str,
        nargs='+',
        help='Path to one or more .las files'
    )
    args = parser.parse_args()
    
    for las_file in args.las_files:
        las_path = Path(las_file)
        if not las_path.exists():
            print(f"ERROR: File not found: {las_path}")
            continue
        
        try:
            analyze_las_file(str(las_path))
        except Exception as e:
            print(f"ERROR analyzing {las_path}: {e}")


if __name__ == "__main__":
    main()
